name: Run Scraper and Commit Changes
on:
  push:
    paths:
      - Scraper.py
      - requirements.txt
  schedule:
    - cron: '0 6 * * *'  # Run at 6:00 UTC daily
  workflow_dispatch:
jobs:
  run-scraper:
    runs-on: ubuntu-latest
    # Add concurrency to prevent overlapping runs
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get full history
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Pull latest changes
        run: |
          git pull origin main
          
      - name: Run scraper
        run: |
          python Scraper.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update data from scraper $(date +%Y-%m-%d)"
            # Try to push, if it fails, pull and try again
            git push origin main || (git pull --rebase origin main && git push origin main)
          else
            echo "No changes to commit."
          fi
