name: Run Model Training and Commit Changes

on:
  push:
    paths:
      - train_models.py
      - requirements.txt
  schedule:
    - cron: '0 6 * * *'  # Run at 6:00
  workflow_dispatch:

jobs:
  run-training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
          token: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run model training
        run: |
          python train_models.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update data from model training"
            git pull --rebase origin main
            git push origin main
          else
            echo "No changes to commit."
