name: Real Estate ML Model Training

on:
  push:
    branches: [ main, master ]
    paths:
      - 'unegui_data/**'
      - 'train_models.py'
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run weekly on Monday at 2AM UTC
    - cron: '0 2 * * 1'
  workflow_dispatch:
    # Allows manual triggering from GitHub UI

jobs:
  train_models:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Train prediction models
      run: |
        python train_models.py
        
    - name: Ensure models directory exists
      run: |
        mkdir -p models
        
    - name: Save models to models directory
      run: |
        # Copy any root directory model files to models directory for consistency
        if [ -f apartment_price_prediction_model.pkl ]; then
          cp apartment_price_prediction_model.pkl models/
        fi
        
    - name: Upload trained models as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-models
        path: models/*.pkl
        retention-days: 90
        
    - name: Commit and push models to repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add models/*.pkl
        git add apartment_price_prediction_model.pkl
        git diff --staged --quiet || git commit -m "Update trained models [skip ci]"
        git push
      continue-on-error: true
